[project]
name = "class-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "markdown2>=2.5.3",
    "openai-agents>=0.0.17",
    "streamlit>=1.45.1",
]
